services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev.server
    ports:
      - "5000:80"
    environment:
      - GPT_API_KEY=${GPT_API_KEY}
      - GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY}
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build:
      context: ./vlangsreact.client
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    security_opt:
      - label=disable
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./vlangsreact.client/src:/app/src
      - ./vlangsreact.client/index.html:/app/index.html