version: "3.9"
services:
  client:
    build: ./vlangsreact.client
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build: ./VLangsReact.Server
    ports:
      - "5000:80"
    environment:
      - GPT_API_KEY=${GPT_API_KEY}
      - GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY}
      - ASPNETCORE_ENVIRONMENT=Development
